#!/usr/bin/env python

import sparql
import sys

if len(sys.argv) != 2:
    print "Usage:\n\tshow_objects <type>\n"
    sys.exit(1)

endpoint = sparql.default_endpoint()

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?obj ?label
WHERE {
  ?obj a <%s>
  OPTIONAL {
    ?obj rdfs:label ?label
  }
}
LIMIT 100
""" % sys.argv[1]

res = sparql.execute_query(endpoint, query)

sparql.pretty_print_results(res, max_column=60)

