#!/usr/bin/env python

import sparql

endpoint = sparql.default_endpoint()

query = """
SELECT DISTINCT ?type ?label
WHERE {
  ?anything a ?type .
  ?type <http://www.w3.org/2000/01/rdf-schema#label> ?label
}
"""

res = sparql.execute_query(endpoint, query)

sparql.pretty_print_results(res)

