#!/usr/bin/env python

import sparql
import sys

if len(sys.argv) != 2:
    print "Usage:\n\tshow_properties <url>\n"
    sys.exit(1)

endpoint = sparql.default_endpoint()

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cybprop: <http://cyberprobe.sf.net/prop/>
PREFIX cybtype: <http://cyberprobe.sf.net/type/>

SELECT ?obs ?label ?src ?dest
WHERE {
  ?obs cybprop:url <%s> .
  ?obs a cybtype:observation .
  ?obs rdfs:label ?label .
  ?obs cybprop:source ?srcip .
  ?srcip cybprop:address ?src .
  ?srcip a cybtype:ipv4 .
  ?obs cybprop:dest ?destip .
  ?destip cybprop:address ?dest .
  ?destip a cybtype:ipv4 .
}
LIMIT 100
""" % sys.argv[1]

res = sparql.execute_query(endpoint, query)

res.output(column_widths={
    'obs': 38,
    'label': 30,
    'src': 15,
    'dest': 15
})

