#!/usr/bin/env python

import sparql
import sys

if len(sys.argv) != 2:
    print "Usage:\n\tshow_properties <ip>\n"
    sys.exit(1)

endpoint = sparql.default_endpoint()

query = """
PREFIX cybprop: <http://cyberprobe.sf.net/prop/>
SELECT ?id
WHERE {
  ?id cybprop:address "%s"
}
LIMIT 1
""" % sys.argv[1]

res = sparql.execute_query(endpoint, query)

if len(res.values) == 0:
   print "No information on that IP Address"
   sys.exit(0)

id = str(res.values[0]['id'])

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cybprop: <http://cyberprobe.sf.net/prop/>
PREFIX cybtype: <http://cyberprobe.sf.net/type/>

SELECT ?label ?dest
WHERE {
  ?obs cybprop:source <%s> .
  ?obs cybprop:dest ?destip .
  ?destip a cybtype:ipv4 .
  ?obs a cybtype:observation .
  ?obs rdfs:label ?label .
  ?destip cybprop:address ?dest
}
LIMIT 100
""" % id

res = sparql.execute_query(endpoint, query)

print "Source of messages:"
print res

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cybprop: <http://cyberprobe.sf.net/prop/>
PREFIX cybtype: <http://cyberprobe.sf.net/type/>

SELECT ?label ?dest
WHERE {
  ?obs cybprop:dest <%s> .
  ?obs a cybtype:observation .
  ?obs rdfs:label ?label .
  ?obs cybprop:source ?destip .
  ?destip a cybtype:ipv4 .
  ?destip cybprop:address ?dest
}
LIMIT 100
""" % id

res = sparql.execute_query(endpoint, query)

print
print "Destination for:"
print res
