#!/usr/bin/env python

import sparql
import sys
import time

if len(sys.argv) != 2:
    print "Usage:\n\tshow_objects <time/s>\n"
    sys.exit(1)

now = time.time()
tht = time.gmtime(now - int(sys.argv[1]))
th = time.strftime("%Y-%m-%dT%H:%M:%SZ", tht)

endpoint = sparql.default_endpoint()

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cybprop: <http://cyberprobe.sf.net/prop/>
PREFIX cybtype: <http://cyberprobe.sf.net/type/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?obj ?label ?time
WHERE {
  ?obj a cybtype:observation .
  OPTIONAL {
    ?obj rdfs:label ?label
  }
  ?obj cybprop:time ?time
  FILTER (?time > "%s"^^xsd:dateTime)
}
ORDER BY DESC(?time)
LIMIT 100
""" % th

print query

res = sparql.execute_query(endpoint, query)

res.output(sys.stdout)

